version: '3.8'

services:
  redis:
    container_name: auth-guard-redis
    image: redis
    ports:
      - '6379:6379'
  database:
    container_name: auth-guard-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: auth-guard
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
