services:
  postgres:
    container_name: container_postgres_apply_flow
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: apply-flow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
